apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - userservice.yaml
components:
  - ../../../components/accounts
  - ../../../../components/backend-service
patches:
  - target:
      kind: Deployment
    path: add-private-key-volume.yaml