###############
# Sonal cloud #
###############
# 1. sonar.host.url=https://sonarcloud.io
# 2. sonar.organization=pruthvi-gcp-devops
# 3. sonar.pojectkey=bank-of-anthos
# 4. sonar.login=04d9bd592f25db1d991090c621540fbed3541f6f

steps:
  #Execute Sonal cloud sourceProvenance:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: mvn
    args: ['verify', 'sonar:sonar',
     '-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=pruthvi-gcp-devops',
     '-Dsonar.porjectkey=bank-of-anthos', '-Dsonar.login=${_SONAR_TOKEN}']
    dir: src/ledger/balancereader
  # Execute SonarCloud sourceProvenance:
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r src/accounts/contacts/requirements.txt
        sonar-scanner \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=pruthvi-gcp-devops \
          -Dsonar.projectKey=bank-of-anthos \
          -Dsonar.login=${_SONAR_TOKEN}
substitutions:
  _SONAR_TOKEN: 04d9bd592f25db1d991090c621540fbed3541f6f
options:
  logging: CLOUD_LOGGING_ONLY