###############
# Sonal cloud #
###############
# 1. sonar.host.url=https://sonarcloud.io
# 2. sonar.organization=pruthvi-gcp-devops
# 3. sonar.pojectkey=bank-of-anthos
# 4. sonar.login=04d9bd592f25db1d991090c621540fbed3541f6f

steps:
  #Execute Sonal cloud sourceProvenance:
  - name: maven:3-jdk-11
    args: ['cd src/ledger/balancereader', 'mvn', 'verify', 'sonar:sonar',
     '-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=pruthvi-gcp-devops',
     '-Dsonar.porjectkey=bank-of-anthos', '-Dsonar.login=${_SONAR_TOKEN}']
substitutions:
  _SONAR_TOKEN: 04d9bd592f25db1d991090c621540fbed3541f6f
options:
  logging: CLOUD_LOGGING_ONLY