steps:
  # Execute Sonar cloud source on accounts contacts service
  - name: ubuntu
    id: contacts-code-scanning
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get -y install maven
        SNYK_TOKEN=${_SNYK_TOKEN}
        export SNYK_TOKEN
        mvn snyk:test -fn

        pip install -r requirements.txt
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.0.2966-linux.zip
        unzip sonar-scanner-cli-5.0.0.2966-linux.zip
        sudo mv sonar-scanner-5.0.0.2966-linux /var/opt
        export PATH=/var/opt/sonar-scanner-5.0.0.2966-linux/bin:$(awk -F'"' '/^PATH/ {print $2}' /etc/environment)
        sonar-scanner \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=pruthvi-gcp-devops \
          -Dsonar.projectKey=contacts \
          -Dsonar.login=${_SONAR_TOKEN}
    dir: src/accounts/contacts
  #Execute Sonar cloud source on accounts userservice service
  - name: ubuntu
    id: userservice-code-scanning
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.0.2966-linux.zip
        unzip sonar-scanner-cli-5.0.0.2966-linux.zip
        sudo mv sonar-scanner-5.0.0.2966-linux /var/opt
        export PATH=/var/opt/sonar-scanner-5.0.0.2966-linux/bin:$(awk -F'"' '/^PATH/ {print $2}' /etc/environment)
        sonar-scanner \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=pruthvi-gcp-devops \
          -Dsonar.projectKey=userservice \
          -Dsonar.login=${_SONAR_TOKEN}
    dir: src/accounts/userservice

substitutions:
  _SONAR_TOKEN: 04d9bd592f25db1d991090c621540fbed3541f6f
  _SNYK_TOKEN: eb8cc27a-1f71-4da3-a196-230d27ebeafb
options:
  env:
  - '_SNYK_TOKEN=$_SNYK_TOKEN'
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY