apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ledgerwriter
requires:
- configs:
  - e2e-tests
  path: ../../../skaffold-e2e.yaml
- configs:
  - ledger-db
  path: ../ledger-db/skaffold.yaml
build:
  artifacts:
  - image: ledgerwriter
    context: ../../../
    jib:
      project: src/ledger/ledgerwriter
      type: maven
  tagPolicy:
    sha256: {}
test:
  - image: ledgerwriter # code style
    context: .
    custom:
      - command: ../../../mvnw checkstyle:check
        timeoutSeconds: 1200
  - image: ledgerwriter # unit tests
    context: .
    custom:
      - command: ../../../mvnw test
        timeoutSeconds: 1200
  - image: ledgerwriter # code coverage
    context: .
    custom:
      - command: |
          ../../../mvnw jacoco:report
          awk -F, \
            '{ instructions += $4 + $5; covered += $5 } END \
            { print covered, "/", instructions, " instructions covered"; \
            print int(100*covered/instructions), "% covered" }' \
            target/site/jacoco/jacoco.csv
        timeoutSeconds: 1200
deploy:
  kubectl: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
      - ../../../iac/acm-multienv-cicd-anthos-autopilot/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
