apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tier: backend
resources:
  - contacts.yaml
components:
  - ../../../components/accounts
  - ../../../../components/backend-service
  - ../../../../components/add-public-key-volume
