apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/init-db-job
  - ../../../../../components/cloud-sql
  - ../../../../../components/production