apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tier: web
  team: frontend
resources:
  - frontend.yaml
components:
  - ../../../components/add-tmp-dir
  - ../../../components/add-public-key-volume
  - ../../../components/bank-of-anthos
