apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
commonLabels:
  application: bank-of-anthos
components:
  - ../istio-proxy-hold-application-patch
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: bank-of-anthos
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccount
        value: bank-of-anthos
