apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: userservice
requires:
- configs:
  - e2e-tests
  path: ../../../skaffold-e2e.yaml
- configs:
  - accounts-db
  path: ../accounts-db/skaffold.yaml
build:
  artifacts:
  - image: userservice
    context: .
  tagPolicy:
    sha256: {}
test:
  - image: userservice # code style
    context: .
    custom:
      - command: |
          pip install pylint --quiet
          pip install -r requirements.txt --quiet
          pylint --rcfile=../../../.pylintrc *.py
        timeoutSeconds: 1200
        dependencies: 
          paths:
            - "**/*.py"
            - "../../../.pylintrc"
            - "requirements.txt"
  - image: userservice # unit tests
    context: .
    custom:
      - command: |
          pip install -r requirements.txt --quiet
          python3 -m pytest -v -p no:warnings
        timeoutSeconds: 1200
        dependencies: 
          paths:
            - "**/*.py"
            - "requirements.txt"
  - image: userservice # code coverage
    context: .
    custom:
      - command: |
          pip install -r requirements.txt --quiet
          python3 -m pytest --cov=./ tests/
        timeoutSeconds: 1200
        dependencies: 
          paths:
            - "**/*.py"
            - "requirements.txt"
deploy:
  kubectl: {}
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
      - ../../../iac/acm-multienv-cicd-anthos-autopilot/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
