steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', $_CACHE_URI, '/workspace/cache'] # always write skaffold cache to filename cache in workspace
  - name: gcr.io/k8s-skaffold/skaffold:v2.9.0
    args:
      - "skaffold"
      - "build"
      - "--file-output=/workspace/artifacts.json"
      - "--default-repo=$_CONTAINER_REGISTRY"
      - "--cache-file=/workspace/$_CACHE" # set _CACHE to anything other than "cache" e.g. "no-cache" to reset skaffold cache
      - "--module=$_TEAM"
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '/workspace/$_CACHE',  $_CACHE_URI]
  - name: gcr.io/k8s-skaffold/skaffold:v2.9.0 # python set up should be baked into a custom builder image to speed up build times
    script: |
      #!/bin/bash
      apt-get update
      apt-get -y install python3-venv
      python3 -m venv $HOME/venv-python-tests
      . $HOME/venv-python-tests/bin/activate
      pip install --upgrade pip
      pip install pylint
      cd /workspace/src/$TEAM
      skaffold test --build-artifacts=/workspace/artifacts.json --assume-yes
    env:
      - 'TEAM=$_TEAM'
  - name: gcr.io/cloud-builders/gcloud
    args: 
      - "deploy"
      - "releases"
      - "create"
      - "$_TEAM-$SHORT_SHA-$$DATE-$$TIME"
      - "--delivery-pipeline=$_TEAM"
      - "--build-artifacts=/workspace/artifacts.json"
      - "--skaffold-file=src/$_TEAM/skaffold.yaml"
      - "--region=$LOCATION"
      - "--gcs-source-staging-dir=$_SOURCE_STAGING_BUCKET/$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY