apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: frontend
requires:
- configs:
  - e2e-tests
  path: ../../skaffold-e2e.yaml
build:
  artifacts:
  - image: frontend
    context: .
  tagPolicy:
    sha256: {}
test:
  - image: frontend # code style
    context: .
    custom:
      - command: |
          pip install pylint --quiet
          pip install -r requirements.txt --quiet
          pylint --rcfile=../../.pylintrc *.py
        timeoutSeconds: 180
        dependencies: 
          paths:
            - "**/*.py"
            - "../../.pylintrc"
            - "requirements.txt"
deploy:
  kubectl: {}
  tolerateFailuresUntilDeadline: true
profiles:
- name: development
  activation:
  - command: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
      - ../../iac/acm-multienv-cicd-anthos-autopilot/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
