apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - backend-config.yaml
  - frontend-config.yaml
  - frontend-ingress.yaml
  - managed-certificate.yaml
components:
  - ../../../../components/production
patchesStrategicMerge:
  - frontend-service.yaml
