apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: accounts-db
deploy:
  kubectl: {}
profiles:
- name: development
  activation:
  - command: dev
  build:
    artifacts:
    - image: accounts-db
      context: .
    tagPolicy:
      sha256: {}
  manifests:
    kustomize:
      paths:
      - k8s/overlays/development
      - ../../../iac/acm-multienv-cicd-anthos-autopilot/overlays/development
- name: staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/staging
- name: production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/production
- name: init-db-staging
  manifests:
    kustomize:
      paths:
      - k8s/overlays/init-db-staging
- name: init-db-production
  manifests:
    kustomize:
      paths:
      - k8s/overlays/init-db-production
