apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tier: db
resources:
  - ../../base
  - accounts-db.yaml
components:
  - ../../../../components/accounts
  - ../../../../../components/development
